export const home = {
  hero: {
    index: "01",
    kicker: "LA CASA DE LOS CAMPEONES",
    title: "LA CASA DE LOS CAMPEONES",
    englishTitle: "THE HOUSE OF THE CHAMPIONS",
    englishWords: ["THE", "HOUSE", "OF", "THE", "CHAMPIONS"],
    lines: ["ENTRENA CON LOS MEJORES.", "CONVIÉRTETE EN EL MEJOR."],
    lead: "Un espacio de entrenamiento de élite para atletas que no buscan solamente estar en forma. Buscan competir, mejorar y estar entre los mejores.",
    image: "/media/hero/kettlebell.jpg",
    imageAlt: "Pesas rusas con luz dramática en La Casa de los Campeones",
  },
  statement: {
    index: "02",
    title: ["NO VENIMOS A SER BUENOS.", "VENIMOS A SER LOS MEJORES."],
    paragraphs: [
      "BBH nace de una idea simple: si quieres llegar a la cima, tienes que entrenar con quienes ya conocen el camino.",
      "Nuestros entrenadores no están aquí solamente para dirigir sesiones. Son especialistas en rendimiento y trabajan para formar atletas capaces de competir al más alto nivel.",
      "Aquí entrenan personas que quieren más.",
    ],
  },
  coaches: {
    index: "03",
    eyebrow: "LOS MEJORES ENTRENADORES",
    title: "NO DIRIGEN CLASES. PREPARAN ATLETAS.",
    lead: "En BBH el entrenador no anima una sesión. Trabaja rendimiento: estándar, programación y exigencia para quien quiere el siguiente nivel.",
  },
  athletes: {
    index: "04",
    eyebrow: "LOS MEJORES ATLETAS",
    title: "ENTRENA DONDE SE COMPITE.",
    lead: "Si te basta con estar en forma, hay muchos otros lugares. Si quieres marcas personales, podios y clasificaciones, entrenas junto a gente que también los persigue.",
    points: ["Atletas competitivos", "Marcas personales y clasificaciones", "Estándar alto en cada sesión"],
    image: "/media/athletes/grip.jpg",
    imageAlt: "Atleta de BBH en un agarre de élite durante el entrenamiento",
  },
  performance: {
    index: "05",
    eyebrow: "RENDIMIENTO DE ÉLITE",
    title: "UN SISTEMA. NO UN GIMNASIO.",
    lead: "Fuerza, motor, entrenamiento híbrido y competencia en una sola arquitectura. Cada clase existe para mover el rendimiento, no para llenar un horario.",
    points: [
      { label: "FUERZA", text: "Fuerza que se transfiere a la competencia." },
      { label: "MOTOR", text: "Capacidad para sostener la intensidad." },
      { label: "HÍBRIDO", text: "Fuerza y condición en el mismo atleta." },
      { label: "COMPITE", text: "El entrenamiento termina en el resultado." },
    ],
  },
  classes: {
    index: "06",
    eyebrow: "SISTEMA DE ENTRENAMIENTO",
    title: "SIETE DIRECCIONES. UN ESTÁNDAR.",
    lead: "Rendimiento HYROX es una pieza. El sistema es más amplio: tren inferior, tren superior, híbrido y motor.",
  },
  hyrox: {
    index: "07",
    eyebrow: "HYROX",
    title: "UN PILAR. NO EL ÚNICO SENTIDO.",
    lead: "BBH entrena HYROX con seriedad: estaciones, transiciones y técnica de competencia. Pero la casa no existe por una carrera. Existe para crear campeones.",
    image: "/media/classes/plate.jpg",
    imageAlt: "Preparación de fuerza e HYROX en el piso de BBH",
  },
  community: {
    index: "08",
    eyebrow: "COMUNIDAD",
    title: "UNA CASA. NO UN GIMNASIO COMERCIAL.",
    lead: "La comunidad de BBH se construye en el piso: gente que se exige, que compite y que eleva a quien entrena a su lado.",
  },
  finalCta: {
    title: "SI QUIERES SER EL MEJOR, ENTRENA CON LOS MEJORES.",
    lead: "BBH no es para quien busca un gimnasio más. Es para quien quiere competir.",
  },
} as const;
